const DEFAULT_PROGRESS_BAR_COLOR = '#BF1E2D'
const DEFAULT_PROGRESS_BAR_BACKGROUND_COLOR = '#999999'
const DEFAULT_PROGRESS_BAR_WIDTH = 20

export {
    DEFAULT_PROGRESS_BAR_COLOR,
    DEFAULT_PROGRESS_BAR_BACKGROUND_COLOR,
    DEFAULT_PROGRESS_BAR_WIDTH
}